# Generated by Django 3.1.6 on 2021-02-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenttesting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('position',), 'verbose_name': 'пункт меню', 'verbose_name_plural': 'Пункты меню'},
        ),
        migrations.AddField(
            model_name='menu',
            name='role',
            field=models.IntegerField(null=True),
        ),
    ]
