# Generated by Django 3.1.6 on 2021-02-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenttesting', '0004_auto_20210207_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
