# Generated by Django 3.1.6 on 2021-02-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenttesting', '0006_auto_20210216_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Задействовать пользователя'),
        ),
    ]
