# Generated by Django 3.1.6 on 2021-02-11 04:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studenttesting', '0007_result_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='completion_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата прохождения'),
        ),
    ]
