# Generated by Django 3.1.6 on 2021-02-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenttesting', '0008_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='completion_date',
            field=models.DateTimeField(default='', verbose_name='Дата прохождения'),
        ),
    ]
