version: "3.7"
services:
  web:
    image: strax88/studenttesting_web
    command: python3 manage.py runserver 0.0.0.0:9000
    ports:
      - 9000:9000
    volumes:
      - ./app/:/home/web/studenttesting/employment_task
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12685
      - POSTGRES_DB=testing_db
  notify:
<<<<<<< HEAD
    image: strax88/studenttesting_web
=======
    image: studenttesting_web
>>>>>>> a8c9f2727e2df06ec62b513887cd6f190c5ed983
    command: python3 manage.py process_tasks
    depends_on:
      - web
volumes:
  postgres_data:
