version: "3.7"
services:
  web:
    build: ./employment_task
    command: bash -c "python3 manage.py loaddata ./studenttesting/fixtures/initial_data.json" # закоментировать после первого запуска docker-compose up
    # command: bash -c "python3 manage.py runserver 0.0.0.0:9000" # раскоментировать после первого запуска docker-compose up
    ports:
      - 9000:9000
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12685
      - POSTGRES_DB=testing_db
  notify:
    image: ./employment_task
    # command: bash -c "python3 manage.py process_tasks # раскоментировать после первого запуска docker-compose up
    depends_on:
      - web
volumes:
  postgres_data:
