# Generated by Django 3.1.6 on 2021-02-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenttesting', '0004_auto_20210216_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступ к панели администратора'),
        ),
    ]
